from flask import Flask, flash, redirect, render_template, request, session, url_for, jsonify
from sys import argv
from server import run_server
import sqlite3
tool_version = 1.0
msg = f"MEP Live View {tool_version}:"
if __name__ == "__main__":
    if len(argv) >= 2:
        if argv[1] == "--help":
            print(f"{msg} This is the diagnostic tool for the MEP Libraries.\n To use it, please specify the path to SQLite database generated by MEPLib")
            exit()
    elif len(argv) != 2:
        print(f"{msg} Incorrect number of arguments: {len(argv)}. For more information please use --help.")
        exit()
    print(f"{msg} Trying to open a data base called: {argv[1]}")
    try:
        database = sqlite3.connect(f"file:{argv[1]}?mode=rw", uri=True, check_same_thread=False)
    except sqlite3.OperationalError:
        print("{msg} Not a database!")
        exit()
    print(f"{msg} Running a server")
    run_server(database)